# Generated by Django 6.0.4 on 2026-06-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlesson',
            name='is_rescheduled_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_slots', to='timetable.scheduledlesson'),
        ),
    ]
