# Generated by Django 6.0.4 on 2026-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_redday'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlesson',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('lab', 'Lab'), ('exam', 'Exam')], default='seminar', max_length=20),
        ),
    ]
