# Generated by Django 6.0.4 on 2026-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_scheduledlesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='final_exam_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='midterm_exam_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='retake_exam_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
