# Generated by Django 6.0.4 on 2026-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_teacher_final_exam_count_teacher_midterm_exam_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlesson',
            name='is_custom_added',
            field=models.BooleanField(default=False),
        ),
    ]
