# Generated by Django 6.0.4 on 2026-06-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_monthlyreport_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='dean_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='dean_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_dean_reviewed', to='timetable.teacher'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='approval_status',
            field=models.CharField(choices=[('pending_dean', 'pending_dean'), ('pending_admin', 'pending_admin'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending_dean', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
    ]
