# Generated by Django 6.0.4 on 2026-06-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_monthlyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('teacher', 'year', 'month')},
        ),
    ]
