# Generated by Django 6.0.4 on 2026-06-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_monthlyreport_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='admin_note',
            new_name='admin_rejection_reason',
        ),
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='approved_at',
            new_name='admin_reviewed_at',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='admin_approval',
            field=models.CharField(choices=[('waiting_dean', 'waiting_dean'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='waiting_dean', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_admin_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='dean_approval',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='dean_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='rejected_by',
        ),
    ]
