# Generated by Django 6.0.4 on 2026-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='final_exam_unit',
            field=models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='midterm_exam_unit',
            field=models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='retake_exam_unit',
            field=models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledlesson',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'lecture'), ('seminar', 'seminar'), ('lab', 'lab'), ('exam', 'exam'), ('final_exam', 'final_exam'), ('midterm_exam', 'midterm_exam'), ('retake_exam', 'retake_exam')], default='seminar', max_length=20),
        ),
    ]
