# Generated by Django 6.0.4 on 2026-07-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_teacher_final_exam_unit_teacher_midterm_exam_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('final_exam_count', models.PositiveIntegerField(default=0)),
                ('final_exam_unit', models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10)),
                ('midterm_exam_count', models.PositiveIntegerField(default=0)),
                ('midterm_exam_unit', models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10)),
                ('retake_exam_count', models.PositiveIntegerField(default=0)),
                ('retake_exam_unit', models.CharField(choices=[('groups', 'groups'), ('students', 'students')], default='students', max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendances', to='timetable.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
    ]
