# Generated by Django 6.0.4 on 2026-07-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_examattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledlesson',
            name='class_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timetablecard',
            name='class_names',
            field=models.TextField(blank=True),
        ),
    ]
